sudo: false  # use new container infrastructure on Travis CI

language: python

python: 2.7

before_install:
  # Install miniconda.
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - rm miniconda.sh
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install -c conda
  - conda info -a  # Useful for debugging any issues with conda

install:
  # create and activate env using NILMTK's environment.yml
  - conda env create 
  - source activate nilmtk-env

  # Install nilm_metadata (can't yet install using pip / conda)
  - pip install -e 'git+https://github.com/nilmtk/nilm_metadata.git#egg=nilm_metadata'

  # Finally, install nilmtk...
  - pip install -e 'git+https://github.com/nilmtk/nilmtk.git#egg=nilmtk'

script:
  - python -c 'from nilmtk.utils import show_versions; show_versions()'
  - nosetests

after_script:
  - source deactivate

cache:
  directories:
    - $HOME/.cache/pip
