name: nilmtk-env
dependencies:
- python=2.7
- Cython>=0.19.1
- bottleneck>=0.6.0
- numpy>=1.8.0
- numexpr>=2.2.2
- pytables
- pandas==0.19.2
- matplotlib
- networkx==1.9.1
- scipy>=0.16.1
- scikit-learn>=0.14
- jupyter
- ipython
- six
- future
- nose
- coverage
- pip
- pip:  # Install packages which are not in conda. Install these using pip:
    - coveralls
    - hmmlearn==0.1.1
    - psycopg2 # not available in conda for Windows.  See issue #462
    - git+https://github.com/nilmtk/nilm_metadata.git#egg=nilm_metadata
    - git+https://github.com/nilmtk/nilmtk.git#egg=nilmtk
    - ipykernel # Needed to get jupyter notebook working with different kernel
