name: nilmtk-env
dependencies:
- python=2.7
- Cython>=0.19.1
- bottleneck>=0.6.0
- numpy>=1.8.0
- numexpr>=2.2.2
- pytables
- pandas>=0.17.1
- matplotlib
- networkx
- scipy
- scikit-learn>=0.14
- ipython
- six
- nose
- coverage
- pip
- pip:  # Install packages which are not in conda. Install these using pip:
    - coveralls
    - hmmlearn==0.1.1
    - psycopg2 # not available in conda for Windows.  See issue #462
