name: nilmtk-env
channels:
    - conda-forge
    - nilmtk
dependencies:
- python>=3.6
- Cython>=0.27.3
- bottleneck>=1.2.1
- numpy>=1.13.3
- numexpr>=2.6.4
- pytables
- pandas>=0.25.3,<1.0
- matplotlib>=3.1.0
- networkx==2.1
- scipy>=1.0.0
- scikit-learn>=0.21.2
- jupyter
- ipython
- ipykernel
- nose
- coverage
- pip
- psycopg2
- coveralls
- nilm_metadata
- nilmtk
- hmmlearn
