name: nilmtk-env
channels:
    - conda-forge
    - nilmtk
dependencies:
- python>=3.6
- numpy>=1.13.3,<1.20
- pytables
- pandas>=0.25.3,<1.0
- matplotlib-base>=3.1.0,<3.2.0
- networkx==2.1
- scipy>=1.0.0
- scikit-learn>=0.21.2
- jupyterlab
- nose
- nilm_metadata
- nilmtk
- hmmlearn
